CREATE FUNCTION CSFCGGETYEAR
 (V_DTNEWDATE TIMESTAMP,
  V_IREPORTTYPE INTEGER
 ) 
  RETURNS SMALLINT
  SPECIFIC SQL051228183828000
  LANGUAGE SQL
  NOT DETERMINISTIC
  READS SQL DATA
  STATIC DISPATCH
  CALLED ON NULL INPUT
  EXTERNAL ACTION
  INHERIT SPECIAL REGISTERS
  BEGIN ATOMIC
    DECLARE v_iMonth INTEGER;
    DECLARE v_iYear INTEGER;
    SET v_iYear = YEAR(V_DTNEWDATE);
    IF V_IREPORTTYPE = 1 THEN
      SET v_iMonth = MONTH(V_DTNEWDATE);
    ELSE
      SET v_iMonth = (MONTH(V_DTNEWDATE) + 2 ) / 3;
    END IF;
    IF v_iMonth = 1 THEN
      SET v_iYear = v_iYear - 1;
    END IF;
    RETURN v_iYear;
  END;
