CREATE FUNCTION CSFCGGETYEAR
 (V_IYEAR INTEGER,
  V_IMONTH INTEGER,
  V_IREPORTTYPE INTEGER
 ) 
  RETURNS SMALLINT
  SPECIFIC SQL051228194135300
  LANGUAGE SQL
  NOT DETERMINISTIC
  READS SQL DATA
  STATIC DISPATCH
  CALLED ON NULL INPUT
  EXTERNAL ACTION
  INHERIT SPECIAL REGISTERS
  BEGIN ATOMIC
    DECLARE v_iComMonth INTEGER;
    DECLARE v_iComYear INTEGER;
    SET v_iComYear = V_IYEAR;
    SET v_iComMonth = V_IMONTH;
    IF V_IREPORTTYPE = 1 THEN
      SET v_iComMonth = v_iComMonth;
    ELSE
      SET v_iComMonth = (v_iComMonth + 2 ) / 3;
    END IF;
    IF v_iComMonth = 1 THEN
      SET v_iComYear = v_iComYear - 1;
    END IF;
    RETURN v_iComYear;
  END;